
import { Teacher, Unit, Day, Campus, Room, TimetableEntry } from './types';

export const CAMPUSES: Campus[] = ['Ultimo', 'Gosford', 'Perth', 'Online'];

export const DAYS: Day[] = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
export const HOURS = Array.from({ length: 24 }, (_, i) => `${i.toString().padStart(2, '0')}:00`);

export const NOVUS_TRAINERS: Teacher[] = [
  { id: 't-asim', name: 'Asim', email: 'asim@novus.edu.au', qualifiedUnits: ['u-adccd-b2'], campuses: ['Perth'], availability: [] },
  { id: 't-bharath', name: 'Bharath', email: 'bharath@novus.edu.au', qualifiedUnits: ['u-dbc', 'u-adccd-b1', 'u-adccd-b2-b3'], campuses: ['Ultimo', 'Online'], availability: [] },
  { id: 't-george', name: 'George', email: 'george@novus.edu.au', qualifiedUnits: ['u-c3aet-b2'], campuses: ['Ultimo'], availability: [] },
  { id: 't-ghanshyam', name: 'Ghanshyam', email: 'ghanshyam@novus.edu.au', qualifiedUnits: ['u-c3aet-b1', 'u-c3lvmt-b1', 'u-c4b', 'u-dam', 'u-dob', 'u-gdm', 'u-adb'], campuses: ['Ultimo', 'Perth', 'Gosford', 'Online'], availability: [] },
  { id: 't-harry', name: 'Harry', email: 'harry@novus.edu.au', qualifiedUnits: ['u-c3bb-b1', 'u-c3pd-b1', 'u-c3wft', 'u-dbc'], campuses: ['Ultimo', 'Online'], availability: [] },
  { id: 't-issa', name: 'Issa', email: 'issakalouche@novus.edu.au', qualifiedUnits: ['u-c3lvmt-b1'], campuses: ['Ultimo'], availability: [] },
  { id: 't-jessy', name: 'Jessy', email: 'jessy@novus.edu.au', qualifiedUnits: ['u-adhm', 'u-c4km-b2', 'u-dhm'], campuses: ['Gosford', 'Ultimo'], availability: [] },
  { id: 't-kabir', name: 'Kabir', email: 'kabir@novus.edu.au', qualifiedUnits: ['u-c4km-b2'], campuses: ['Ultimo'], availability: [] },
  { id: 't-krunal', name: 'Krunal', email: 'krunal@novus.edu.au', qualifiedUnits: ['u-c3aet-b1', 'u-c3lvmt-b2', 'u-dam'], campuses: ['Ultimo'], availability: [] },
  { id: 't-kylie', name: 'Kylie', email: 'kylie@novus.edu.au', qualifiedUnits: ['u-elicos-b1'], campuses: ['Ultimo'], availability: [] },
  { id: 't-lakshmee', name: 'Lakshmee', email: 'lakshmee@novus.edu.au', qualifiedUnits: ['u-elicos-b2'], campuses: ['Ultimo'], availability: [] },
  { id: 't-madan', name: 'Madan', email: 'madan@novus.edu.au', qualifiedUnits: ['u-adhm', 'u-adhm-ct', 'u-dhm'], campuses: ['Gosford', 'Ultimo', 'Perth', 'Online'], availability: [] },
  { id: 't-maxine', name: 'Maxine', email: 'maxine@novus.edu.au', qualifiedUnits: ['u-adcsm', 'u-adcsm-a', 'u-adcsm-b', 'u-adcsm-ict', 'u-dcs'], campuses: ['Perth', 'Gosford', 'Ultimo', 'Online'], availability: [] },
  { id: 't-meena', name: 'Meena', email: 'meena@novus.edu.au', qualifiedUnits: ['u-adcsm'], campuses: ['Perth'], availability: [] },
  { id: 't-praveen', name: 'Praveen', email: 'praveen@novus.edu.au', qualifiedUnits: ['u-c4km-b1'], campuses: ['Ultimo'], availability: [] },
  { id: 't-rebecca', name: 'Rebecca', email: 'rebecca@novus.edu.au', qualifiedUnits: ['u-dcs'], campuses: ['Ultimo'], availability: [] },
  { id: 't-raihan', name: 'Raihan', email: 'raihan@novus.edu.au', qualifiedUnits: ['u-adhm', 'u-adhm-ct', 'u-c4km', 'u-dhm', 'u-gdm'], campuses: ['Perth'], availability: [] },
  { id: 't-sagar', name: 'Sagar', email: 'sagar@novus.edu.au', qualifiedUnits: ['u-c4km-b1', 'u-c4km-b2', 'u-c4km', 'u-dhm', 'u-adhm', 'u-gdm'], campuses: ['Ultimo', 'Gosford', 'Perth', 'Online'], availability: [] },
  { id: 't-sajal', name: 'Dr. Sajal', email: 'sajal@novus.edu.au', qualifiedUnits: ['u-adcsm-b'], campuses: ['Ultimo'], availability: [] },
  { id: 't-sullaiman', name: 'Sullaiman', email: 'sullaiman@novus.edu.au', qualifiedUnits: ['u-c3bb-b1', 'u-c3bb-b2', 'u-c3wft'], campuses: ['Ultimo'], availability: [] },
  { id: 't-sushil', name: 'Sushil', email: 'sushil@novus.edu.au', qualifiedUnits: ['u-adb', 'u-dob', 'u-gdm'], campuses: ['Ultimo', 'Gosford'], availability: [] },
  { id: 't-taran', name: 'Taran', email: 'taran@novus.edu.au', qualifiedUnits: ['u-adcsm', 'u-dcs'], campuses: ['Gosford'], availability: [] },
  { id: 't-vikesh', name: 'Vikesh', email: 'vikesh@novus.edu.au', qualifiedUnits: ['u-c3aet-b1', 'u-c3aet-b2', 'u-c3lvmt-b2'], campuses: ['Ultimo'], availability: [] }
];

export const NOVUS_UNITS: Unit[] = [
  { id: 'u-adccd-b2', name: 'ADCCD B2', type: 'online', durationHours: 20, sessionsPerWeek: 2 },
  { id: 'u-adccd-b1', name: 'ADCCD B1', type: 'theory', durationHours: 20, sessionsPerWeek: 3 },
  { id: 'u-adccd-b2-b3', name: 'ADCCD B2/B3', type: 'online', durationHours: 20, sessionsPerWeek: 3 },
  { id: 'u-dbc', name: 'DBC', type: 'theory', durationHours: 20, sessionsPerWeek: 2 },
  { id: 'u-c3aet-b2', name: 'C3AET B2', type: 'practical', durationHours: 15, sessionsPerWeek: 2 },
  { id: 'u-c3aet-b1', name: 'C3AET B1', type: 'online', durationHours: 15, sessionsPerWeek: 2 },
  { id: 'u-c3lvmt-b1', name: 'C3LVMT B1', type: 'practical', durationHours: 15, sessionsPerWeek: 2 },
  { id: 'u-c3lvmt-b2', name: 'C3LVMT B2', type: 'practical', durationHours: 15, sessionsPerWeek: 2 },
  { id: 'u-c4b', name: 'C4B', type: 'theory', durationHours: 20, sessionsPerWeek: 3 },
  { id: 'u-dam', name: 'DAM', type: 'online', durationHours: 20, sessionsPerWeek: 3 },
  { id: 'u-dob', name: 'DOB', type: 'theory', durationHours: 20, sessionsPerWeek: 2 },
  { id: 'u-gdm', name: 'GDM', type: 'online', durationHours: 20, sessionsPerWeek: 3 },
  { id: 'u-adb', name: 'ADB', type: 'theory', durationHours: 20, sessionsPerWeek: 2 },
  { id: 'u-c3bb-b1', name: 'C3BB B1', type: 'online', durationHours: 15, sessionsPerWeek: 2 },
  { id: 'u-c3bb-b2', name: 'C3BB B2', type: 'online', durationHours: 15, sessionsPerWeek: 2 },
  { id: 'u-c3pd-b1', name: 'C3PD B1', type: 'practical', durationHours: 15, sessionsPerWeek: 4 },
  { id: 'u-c3pd-b2', name: 'C3PD B2', type: 'practical', durationHours: 15, sessionsPerWeek: 4 },
  { id: 'u-c3wft', name: 'C3WFT', type: 'online', durationHours: 15, sessionsPerWeek: 2 },
  { id: 'u-adhm', name: 'ADHM', type: 'theory', durationHours: 20, sessionsPerWeek: 3 },
  { id: 'u-adhm-ct', name: 'ADHM CT', type: 'online', durationHours: 20, sessionsPerWeek: 2 },
  { id: 'u-dhm', name: 'DHM', type: 'theory', durationHours: 20, sessionsPerWeek: 3 },
  { id: 'u-c4km-b1', name: 'C4KM B1', type: 'theory', durationHours: 20, sessionsPerWeek: 3 },
  { id: 'u-c4km-b2', name: 'C4KM B2', type: 'theory', durationHours: 20, sessionsPerWeek: 3 },
  { id: 'u-c4km', name: 'C4KM', type: 'online', durationHours: 20, sessionsPerWeek: 2 },
  { id: 'u-elicos-b1', name: 'ELICOS B1', type: 'theory', durationHours: 20, sessionsPerWeek: 4 },
  { id: 'u-elicos-b2', name: 'ELICOS B2', type: 'theory', durationHours: 20, sessionsPerWeek: 4 },
  { id: 'u-adcsm', name: 'ADCSM', type: 'theory', durationHours: 20, sessionsPerWeek: 3 },
  { id: 'u-adcsm-a', name: 'ADCSM Group A', type: 'online', durationHours: 20, sessionsPerWeek: 3 },
  { id: 'u-adcsm-b', name: 'ADCSM Group B', type: 'online', durationHours: 20, sessionsPerWeek: 3 },
  { id: 'u-adcsm-ict', name: 'ADCSM ICT', type: 'online', durationHours: 20, sessionsPerWeek: 3 },
  { id: 'u-dcs', name: 'DCS', type: 'theory', durationHours: 20, sessionsPerWeek: 3 }
];

export const NOVUS_ROOMS: Room[] = [
  { id: 'r-p1', name: 'Unit 53 188 Newcastle St PERTH WA 6000', capacity: 30, campus: 'Perth' },
  { id: 'r-online', name: 'Online', capacity: 100, campus: 'Online' },
  { id: 'r-mountain', name: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007', capacity: 30, campus: 'Ultimo' },
  { id: 'r-gilba', name: '145 Gilba Road, Girraween NSW', capacity: 30, campus: 'Ultimo' },
  { id: 'r-granville', name: 'Unit 1A, 8 Kendall St, Granville NSW 2142', capacity: 30, campus: 'Ultimo' },
  { id: 'r-gos1', name: '153 Mann Street, Level 1, Suite 5, Gosford NSW 2250', capacity: 30, campus: 'Gosford' },
  { id: 'r-gos2', name: '5/131 Henry Parry Drive, Gosford', capacity: 25, campus: 'Gosford' },
  { id: 'r-shop', name: 'Shop 7/68 Mountain St, Ultimo NSW 2007', capacity: 20, campus: 'Ultimo' }
];

export const NOVUS_SCHEDULE_RAW: Partial<TimetableEntry>[] = [
  { unitId: 'u-adccd-b2', teacherId: 't-asim', day: 'Saturday', startTime: '09:30', endTime: '16:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-adccd-b2', teacherId: 't-asim', day: 'Sunday', startTime: '09:30', endTime: '18:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-adccd-b2', teacherId: 't-bharath', day: 'Thursday', startTime: '10:00', endTime: '16:30', room: 'Online' },
  { unitId: 'u-dbc', teacherId: 't-bharath', day: 'Wednesday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adccd-b1', teacherId: 't-bharath', day: 'Thursday', startTime: '12:00', endTime: '18:30', room: 'Online' },
  { unitId: 'u-adccd-b1', teacherId: 't-bharath', day: 'Monday', startTime: '09:30', endTime: '16:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adccd-b1', teacherId: 't-bharath', day: 'Tuesday', startTime: '09:30', endTime: '18:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adccd-b2-b3', teacherId: 't-bharath', day: 'Thursday', startTime: '12:00', endTime: '18:30', room: 'Online' },
  { unitId: 'u-adccd-b2-b3', teacherId: 't-bharath', day: 'Saturday', startTime: '09:30', endTime: '18:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adccd-b2-b3', teacherId: 't-bharath', day: 'Friday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-c3aet-b2', teacherId: 't-george', day: 'Monday', startTime: '17:00', endTime: '21:00', room: '145 Gilba Road, Girraween NSW' },
  { unitId: 'u-c3aet-b2', teacherId: 't-george', day: 'Tuesday', startTime: '17:00', endTime: '21:00', room: '145 Gilba Road, Girraween NSW' },
  { unitId: 'u-c3aet-b1', teacherId: 't-ghanshyam', day: 'Friday', startTime: '09:30', endTime: '16:00', room: 'Online' },
  { unitId: 'u-c3aet-b2', teacherId: 't-ghanshyam', day: 'Friday', startTime: '09:30', endTime: '16:00', room: 'Online' },
  { unitId: 'u-c3lvmt-b1', teacherId: 't-ghanshyam', day: 'Friday', startTime: '09:30', endTime: '16:00', room: 'Online' },
  { unitId: 'u-c3lvmt-b2', teacherId: 't-ghanshyam', day: 'Friday', startTime: '09:30', endTime: '16:00', room: 'Online' },
  { unitId: 'u-c4b', teacherId: 't-ghanshyam', day: 'Tuesday', startTime: '09:00', endTime: '15:30', room: 'Online' },
  { unitId: 'u-c4b', teacherId: 't-ghanshyam', day: 'Monday', startTime: '14:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-c4b', teacherId: 't-ghanshyam', day: 'Tuesday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-dam', teacherId: 't-ghanshyam', day: 'Friday', startTime: '09:30', endTime: '16:00', room: 'Online' },
  { unitId: 'u-dob', teacherId: 't-ghanshyam', day: 'Tuesday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-dob', teacherId: 't-ghanshyam', day: 'Friday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-gdm', teacherId: 't-ghanshyam', day: 'Tuesday', startTime: '09:00', endTime: '15:30', room: 'Online' },
  { unitId: 'u-gdm', teacherId: 't-ghanshyam', day: 'Tuesday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-adb', teacherId: 't-ghanshyam', day: 'Tuesday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-c3bb-b1', teacherId: 't-harry', day: 'Wednesday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-c3bb-b2', teacherId: 't-harry', day: 'Wednesday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-c3pd-b1', teacherId: 't-harry', day: 'Wednesday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-c3pd-b1', teacherId: 't-harry', day: 'Monday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-c3pd-b2', teacherId: 't-harry', day: 'Wednesday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-c3pd-b2', teacherId: 't-harry', day: 'Monday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-c3pd-b1', teacherId: 't-harry', day: 'Monday', startTime: '11:00', endTime: '13:00', room: 'Unit 1A, 8 Kendall St, Granville NSW 2142' },
  { unitId: 'u-c3pd-b1', teacherId: 't-harry', day: 'Saturday', startTime: '08:00', endTime: '14:30', room: 'Unit 1A, 8 Kendall St, Granville NSW 2142' },
  { unitId: 'u-c3pd-b2', teacherId: 't-harry', day: 'Monday', startTime: '13:00', endTime: '15:00', room: 'Unit 1A, 8 Kendall St, Granville NSW 2142' },
  { unitId: 'u-c3pd-b2', teacherId: 't-harry', day: 'Saturday', startTime: '14:30', endTime: '21:00', room: 'Unit 1A, 8 Kendall St, Granville NSW 2142' },
  { unitId: 'u-c3wft', teacherId: 't-harry', day: 'Wednesday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-dbc', teacherId: 't-harry', day: 'Tuesday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-dbc', teacherId: 't-bharath', day: 'Thursday', startTime: '14:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-c3lvmt-b1', teacherId: 't-issa', day: 'Saturday', startTime: '09:30', endTime: '16:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adhm', teacherId: 't-jessy', day: 'Friday', startTime: '09:30', endTime: '18:00', room: '153 Mann Street, Level 1, Suite 5, Gosford NSW 2250' },
  { unitId: 'u-c4km-b2', teacherId: 't-jessy', day: 'Tuesday', startTime: '13:30', endTime: '22:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-dhm', teacherId: 't-jessy', day: 'Wednesday', startTime: '09:30', endTime: '16:00', room: '153 Mann Street, Level 1, Suite 5, Gosford NSW 2250' },
  { unitId: 'u-c4km-b2', teacherId: 't-kabir', day: 'Monday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-c3aet-b1', teacherId: 't-krunal', day: 'Wednesday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-c3lvmt-b2', teacherId: 't-krunal', day: 'Wednesday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-dam', teacherId: 't-krunal', day: 'Sunday', startTime: '09:30', endTime: '18:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-dam', teacherId: 't-krunal', day: 'Saturday', startTime: '09:30', endTime: '16:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-elicos-b1', teacherId: 't-kylie', day: 'Monday', startTime: '17:30', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-elicos-b1', teacherId: 't-kylie', day: 'Tuesday', startTime: '17:00', endTime: '22:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-elicos-b1', teacherId: 't-kylie', day: 'Wednesday', startTime: '17:00', endTime: '22:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-elicos-b1', teacherId: 't-kylie', day: 'Thursday', startTime: '17:00', endTime: '22:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-elicos-b2', teacherId: 't-lakshmee', day: 'Tuesday', startTime: '17:00', endTime: '22:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-elicos-b2', teacherId: 't-lakshmee', day: 'Wednesday', startTime: '17:00', endTime: '22:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-elicos-b2', teacherId: 't-lakshmee', day: 'Friday', startTime: '16:00', endTime: '21:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-elicos-b2', teacherId: 't-lakshmee', day: 'Thursday', startTime: '17:00', endTime: '22:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adhm', teacherId: 't-madan', day: 'Monday', startTime: '09:30', endTime: '16:00', room: 'Online' },
  { unitId: 'u-adhm', teacherId: 't-madan', day: 'Friday', startTime: '09:30', endTime: '16:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adhm-ct', teacherId: 't-madan', day: 'Monday', startTime: '09:00', endTime: '15:30', room: 'Online' },
  { unitId: 'u-adhm', teacherId: 't-madan', day: 'Tuesday', startTime: '09:30', endTime: '18:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-dhm', teacherId: 't-madan', day: 'Monday', startTime: '09:30', endTime: '16:00', room: 'Online' },
  { unitId: 'u-dhm', teacherId: 't-madan', day: 'Wednesday', startTime: '07:30', endTime: '14:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-dhm', teacherId: 't-madan', day: 'Thursday', startTime: '07:30', endTime: '16:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adcsm', teacherId: 't-maxine', day: 'Thursday', startTime: '09:00', endTime: '15:30', room: 'Online' },
  { unitId: 'u-adcsm-a', teacherId: 't-maxine', day: 'Wednesday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-adcsm-b', teacherId: 't-maxine', day: 'Wednesday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-adcsm-ict', teacherId: 't-maxine', day: 'Wednesday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-adcsm-a', teacherId: 't-maxine', day: 'Thursday', startTime: '08:30', endTime: '17:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adcsm-a', teacherId: 't-maxine', day: 'Friday', startTime: '09:30', endTime: '16:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adcsm-ict', teacherId: 't-maxine', day: 'Monday', startTime: '09:30', endTime: '16:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adcsm-ict', teacherId: 't-maxine', day: 'Tuesday', startTime: '08:30', endTime: '17:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-dcs', teacherId: 't-maxine', day: 'Thursday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-dcs', teacherId: 't-maxine', day: 'Wednesday', startTime: '11:00', endTime: '17:30', room: 'Online' },
  { unitId: 'u-adcsm', teacherId: 't-meena', day: 'Thursday', startTime: '17:00', endTime: '21:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-adcsm', teacherId: 't-meena', day: 'Tuesday', startTime: '17:00', endTime: '22:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-adcsm', teacherId: 't-meena', day: 'Wednesday', startTime: '17:00', endTime: '22:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-c4km-b1', teacherId: 't-praveen', day: 'Thursday', startTime: '09:30', endTime: '18:00', room: 'Shop 7/68 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-dcs', teacherId: 't-rebecca', day: 'Monday', startTime: '09:30', endTime: '16:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-dcs', teacherId: 't-rebecca', day: 'Tuesday', startTime: '08:30', endTime: '17:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adhm', teacherId: 't-raihan', day: 'Friday', startTime: '09:30', endTime: '18:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-adhm', teacherId: 't-raihan', day: 'Thursday', startTime: '15:30', endTime: '22:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-adhm-ct', teacherId: 't-raihan', day: 'Friday', startTime: '09:30', endTime: '18:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-adhm-ct', teacherId: 't-raihan', day: 'Thursday', startTime: '15:30', endTime: '22:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-c4km', teacherId: 't-raihan', day: 'Wednesday', startTime: '09:30', endTime: '16:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-c4km', teacherId: 't-raihan', day: 'Thursday', startTime: '09:30', endTime: '18:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-dhm', teacherId: 't-raihan', day: 'Wednesday', startTime: '09:30', endTime: '16:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-dhm', teacherId: 't-raihan', day: 'Thursday', startTime: '09:30', endTime: '18:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-gdm', teacherId: 't-raihan', day: 'Saturday', startTime: '09:30', endTime: '16:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-gdm', teacherId: 't-raihan', day: 'Sunday', startTime: '09:30', endTime: '18:00', room: 'Unit 53 188 Newcastle St PERTH WA 6000' },
  { unitId: 'u-c4km-b1', teacherId: 't-sagar', day: 'Monday', startTime: '09:30', endTime: '16:00', room: 'Online' },
  { unitId: 'u-c4km-b1', teacherId: 't-sagar', day: 'Wednesday', startTime: '09:30', endTime: '16:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-c4km-b2', teacherId: 't-sagar', day: 'Monday', startTime: '08:00', endTime: '14:30', room: '5/131 Henry Parry Drive, Gosford' },
  { unitId: 'u-c4km-b2', teacherId: 't-sagar', day: 'Tuesday', startTime: '09:30', endTime: '16:00', room: '153 Mann Street, Level 1, Suite 5, Gosford NSW 2250' },
  { unitId: 'u-c4km-b2', teacherId: 't-sagar', day: 'Thursday', startTime: '09:30', endTime: '18:00', room: '153 Mann Street, Level 1, Suite 5, Gosford NSW 2250' },
  { unitId: 'u-c4km-b2', teacherId: 't-sagar', day: 'Monday', startTime: '08:00', endTime: '14:30', room: 'Online' },
  { unitId: 'u-c4km', teacherId: 't-sagar', day: 'Monday', startTime: '09:00', endTime: '15:30', room: 'Online' },
  { unitId: 'u-dhm', teacherId: 't-sagar', day: 'Monday', startTime: '09:00', endTime: '15:30', room: 'Online' },
  { unitId: 'u-adhm', teacherId: 't-sagar', day: 'Monday', startTime: '09:00', endTime: '15:30', room: 'Online' },
  { unitId: 'u-gdm', teacherId: 't-sagar', day: 'Saturday', startTime: '09:30', endTime: '18:00', room: '153 Mann Street, Level 1, Suite 5, Gosford NSW 2250' },
  { unitId: 'u-gdm', teacherId: 't-sagar', day: 'Friday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adcsm-b', teacherId: 't-sajal', day: 'Thursday', startTime: '08:30', endTime: '17:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adcsm-b', teacherId: 't-sajal', day: 'Friday', startTime: '09:30', endTime: '16:00', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-c3bb-b1', teacherId: 't-sullaiman', day: 'Thursday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-c3bb-b2', teacherId: 't-sullaiman', day: 'Thursday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-c3wft', teacherId: 't-sullaiman', day: 'Saturday', startTime: '09:30', endTime: '18:00', room: 'Unit 1A, 8 Kendall St, Granville NSW 2142' },
  { unitId: 'u-c3wft', teacherId: 't-sullaiman', day: 'Friday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-c3bb-b1', teacherId: 't-sullaiman', day: 'Thursday', startTime: '09:30', endTime: '11:30', room: 'Unit 1A, 8 Kendall St, Granville NSW 2142' },
  { unitId: 'u-c3bb-b2', teacherId: 't-sullaiman', day: 'Thursday', startTime: '11:30', endTime: '13:30', room: 'Unit 1A, 8 Kendall St, Granville NSW 2142' },
  { unitId: 'u-adb', teacherId: 't-sushil', day: 'Thursday', startTime: '14:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adb', teacherId: 't-sushil', day: 'Friday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-dob', teacherId: 't-sushil', day: 'Monday', startTime: '14:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-gdm', teacherId: 't-sushil', day: 'Wednesday', startTime: '14:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-adcsm', teacherId: 't-taran', day: 'Friday', startTime: '09:30', endTime: '18:00', room: '153 Mann Street, Level 1, Suite 5, Gosford NSW 2250' },
  { unitId: 'u-adcsm', teacherId: 't-taran', day: 'Saturday', startTime: '09:30', endTime: '16:00', room: '153 Mann Street, Level 1, Suite 5, Gosford NSW 2250' },
  { unitId: 'u-dcs', teacherId: 't-taran', day: 'Friday', startTime: '09:30', endTime: '18:00', room: '153 Mann Street, Level 1, Suite 5, Gosford NSW 2250' },
  { unitId: 'u-dcs', teacherId: 't-taran', day: 'Saturday', startTime: '09:30', endTime: '16:00', room: '153 Mann Street, Level 1, Suite 5, Gosford NSW 2250' },
  { unitId: 'u-c3aet-b1', teacherId: 't-vikesh', day: 'Tuesday', startTime: '08:30', endTime: '17:30', room: '145 Gilba Road, Girraween NSW' },
  { unitId: 'u-c3aet-b2', teacherId: 't-vikesh', day: 'Wednesday', startTime: '16:00', endTime: '22:30', room: 'Level 3, Suite 3.09-3.11 22/36 Mountain St, Ultimo NSW 2007' },
  { unitId: 'u-c3lvmt-b2', teacherId: 't-vikesh', day: 'Tuesday', startTime: '08:30', endTime: '17:00', room: '145 Gilba Road, Girraween NSW' },
  { unitId: 'u-c3lvmt-b1', teacherId: 't-issa', day: 'Sunday', startTime: '09:30', endTime: '18:00', room: '145 Gilba Road, Girraween NSW' },
  { unitId: 'u-c3bb-b1', teacherId: 't-sullaiman', day: 'Sunday', startTime: '08:00', endTime: '14:30', room: 'Unit 1A, 8 Kendall St, Granville NSW 2142' },
  { unitId: 'u-c3bb-b2', teacherId: 't-sullaiman', day: 'Sunday', startTime: '14:30', endTime: '21:00', room: 'Unit 1A, 8 Kendall St, Granville NSW 2142' }
];

export const INITIAL_TEACHERS: Teacher[] = NOVUS_TRAINERS;
export const INITIAL_UNITS: Unit[] = NOVUS_UNITS;
export const INITIAL_RULES: string[] = [
  "Teachers cannot teach two classes simultaneously.",
  "Teachers must be qualified for assigned units.",
  "No overlapping of rooms in the same campus at the same time."
];
